Repository cfpb/consumerfinance.gov, pull requests merged in 2019-09, with the labels that each got.

#5210 YES tool - Adds reducer for goals
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/goal-reducer.js
  test/unit_tests/apps/youth-employment-success/js/reducers/goal-reducer-spec.js
Labels: Front-end

#5211 YES tool — Adds basic html for goal-setting section
  cfgov/jinja2/v1/youth_employment_success/budget-form.html
  cfgov/jinja2/v1/youth_employment_success/goals.html
  cfgov/jinja2/v1/youth_employment_success/goals/goal.html
  cfgov/jinja2/v1/youth_employment_success/index.html
  cfgov/unprocessed/apps/youth-employment-success/css/main.less
Labels: Front-end

#5208 YES tool — Hides checkboxes in a no-js environment
  cfgov/jinja2/v1/youth_employment_success/index.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-total-cost.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
  cfgov/unprocessed/apps/youth-employment-success/css/main.less
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/input-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/util.js
  cfgov/unprocessed/js/organisms/BureauStructure.js
Labels: Front-end

#5204 YES tool — Adds new combo field view for transit time
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-total-cost.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/input.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
  cfgov/unprocessed/apps/youth-employment-success/css/main.less
  cfgov/unprocessed/apps/youth-employment-success/js/input-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-toggle-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/route.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js
Labels: Front-end

#5216 YES tool — Add entries helper function
  cfgov/unprocessed/apps/youth-employment-success/js/input-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/util.js
  test/unit_tests/apps/youth-employment-success/js/util-spec.js
Labels: Front-end

#5221 YES tool— Fix syntax error in template
  cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
Labels: Front-end, [issue-type] bug, priority: high

#5223 Fix download on rural or underserved tool
  cfgov/jinja2/v1/rural-or-underserved/index.html
  cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js
Labels: [issue-type] bug

#5220 YES tool — JS view and associated HTML for route details section (WIP)
  cfgov/jinja2/v1/youth_employment_success/alert-icon.html
  cfgov/jinja2/v1/youth_employment_success/alert.html
  cfgov/jinja2/v1/youth_employment_success/route-details.html
  cfgov/jinja2/v1/youth_employment_success/route-option-form.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-daily-cost.html
  cfgov/unprocessed/apps/youth-employment-success/js/data/todo-items.js
  cfgov/unprocessed/apps/youth-employment-success/js/data/transportation-map.js
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/money.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/route.js
  cfgov/unprocessed/apps/youth-employment-success/js/util.js
  cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
  test/unit_tests/apps/youth-employment-success/js/money-spec.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-spec.js
  test/unit_tests/apps/youth-employment-success/js/util-spec.js
  test/unit_tests/apps/youth-employment-success/js/validators/route-option-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js
Labels: Front-end

#5233 YES tool — FIxes bug in route-option validator
  cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js
  test/unit_tests/apps/youth-employment-success/js/validators/route-option-spec.js
Labels: Front-end

#5227 YES Tool — Average cost combo field
  cfgov/jinja2/v1/youth_employment_success/route-option-form.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html
  cfgov/unprocessed/apps/youth-employment-success/js/data/todo-items.js
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js
Labels: Front-end

#5251 Remove invalid polyfills ref
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
Labels: Front-end, priority: high

#5235 YES tool — Add view for `daysPerWeek` fields
  cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Labels: Front-end

#5248 YES tool — Add view for closed route option
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/expandable.js
  test/unit_tests/apps/youth-employment-success/js/views/expandable-spec.js
Labels: Front-end

#5250 YES tool - Adds combo field view for `miles` app state
  cfgov/jinja2/v1/youth_employment_success/alert.html
  cfgov/jinja2/v1/youth_employment_success/index.html
  cfgov/jinja2/v1/youth_employment_success/review/next-steps.html
  cfgov/jinja2/v1/youth_employment_success/review/print.html
  cfgov/jinja2/v1/youth_employment_success/review/review.html
  cfgov/jinja2/v1/youth_employment_success/review/yes-info-unit.html
  cfgov/jinja2/v1/youth_employment_success/review/your-goals.html
  cfgov/jinja2/v1/youth_employment_success/review/your-plan.html
  cfgov/jinja2/v1/youth_employment_success/route-details.html
  cfgov/jinja2/v1/youth_employment_success/route-option-form.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html
  cfgov/jinja2/v1/youth_employment_success/success-icon.html
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/expandable-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js
  test/unit_tests/mocks/store.js
Labels: Front-end

#5244 YES Tool - Adds view for managing goals section form controls
  cfgov/jinja2/v1/youth_employment_success/goals.html
  cfgov/jinja2/v1/youth_employment_success/goals/goal.html
  cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/goal-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/store.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/goals.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/input.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js
  test/unit_tests/apps/youth-employment-success/js/input-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/goals-spec.js
Labels: Front-end

#5255 YES tool — Light cleanup and tweaks
  cfgov/jinja2/v1/youth_employment_success/goals/goal.html
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js
Labels: Front-end, priority: high

#5242 YES tool — Fixes budget calculation bugs
  cfgov/unprocessed/apps/youth-employment-success/js/money.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
  test/unit_tests/apps/youth-employment-success/js/money-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js
Labels: Front-end

#5259 YES tool — Add todo notification behavior
  cfgov/jinja2/v1/youth_employment_success/alert-icon.html
  cfgov/jinja2/v1/youth_employment_success/alert.html
  cfgov/jinja2/v1/youth_employment_success/route-option-form.html
  cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
  cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js
  test/unit_tests/apps/youth-employment-success/fixtures/todo-alert.js
  test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
  test/unit_tests/apps/youth-employment-success/js/todo-notification-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js
  test/unit_tests/apps/youth-employment-success/mocks/todo-notification.js
  test/unit_tests/mocks/store.js
Labels: Front-end

#5260 YES Tool — Adds review goals view and spec
  cfgov/jinja2/v1/youth_employment_success/review/your-goals.html
  cfgov/jinja2/v1/youth_employment_success/review/your-plan.html
  cfgov/unprocessed/apps/youth-employment-success/img/review/learn_about_buying_a_car.png
  cfgov/unprocessed/apps/youth-employment-success/img/review/learn_about_credit.png
  cfgov/unprocessed/apps/youth-employment-success/img/review/opening_a_bank_account.png
  cfgov/unprocessed/apps/youth-employment-success/img/review/track_spending.png
  cfgov/unprocessed/apps/youth-employment-success/js/index.js
  cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/goals.js
  cfgov/unprocessed/apps/youth-employment-success/js/views/review/goals.js
  test/unit_tests/apps/youth-employment-success/js/views/goals-spec.js
  test/unit_tests/apps/youth-employment-success/js/views/review/goals-spec.js
Labels: Front-end
