Repository cfpb/consumerfinance.gov, pull requests merged in 2021-04, with the labels that each got.

#6324 Upgrade to Wagtail 2.12.3
  cfgov/ask_cfpb/scripts/export_ask_data.py
  cfgov/ask_cfpb/tests/models/test_pages.py
  cfgov/ask_cfpb/tests/test_blocks.py
  cfgov/data_research/research_conference.py
  cfgov/mega_menu/management/commands/export_mega_menu.py
  cfgov/mega_menu/tests/management/commands/test_import_mega_menu.py
  cfgov/paying_for_college/tests/test_models.py
  cfgov/scripts/export_enforcement_actions.py
  cfgov/scripts/fix_links_in_tableblocks.py
  cfgov/scripts/tests/test_export_enforcement_actions.py
  cfgov/scripts/tests/test_fix_links_in_tableblocks.py
  cfgov/scripts/update_oaa_status.py
  cfgov/v1/management/commands/update_chart_block_dates.py
  cfgov/v1/management/commands/update_data_snapshot_values.py
  cfgov/v1/migrations/0255_fix_wagtailembeds_constraint.py
  cfgov/v1/tests/atomic_elements/organisms/test_email_signup.py
  cfgov/v1/tests/util/test_migrations.py
  cfgov/v1/util/migrations.py
  docs/migrations.md
  requirements/wagtail.txt
  tox.ini
Labels: Back-end

#6344 Cleanup filter lists
  cfgov/cfgov/settings/base.py
  cfgov/v1/atomic_elements/organisms.py
  cfgov/v1/forms.py
  cfgov/v1/migrations/0256_remove_filter_sibling_choice.py
  cfgov/v1/models/filterable_list_mixins.py
  cfgov/v1/tests/atomic_elements/test_molecules.py
  cfgov/v1/tests/jinja2tags/test_fragment_cache.py
  cfgov/v1/tests/management/commands/test_archive_pages.py
  cfgov/v1/tests/management/commands/test_restore_archive_pages.py
  cfgov/v1/tests/models/test_browse_filterable_page.py
  cfgov/v1/tests/models/test_filterable_list_mixins.py
  cfgov/v1/tests/models/test_sublanding_page.py
  cfgov/v1/tests/test_filterable_list_form.py
  cfgov/v1/tests/test_forms.py
Labels: hold

#6318 TDP: Add additional document upload fields to support Spanish files
  cfgov/locale/es/LC_MESSAGES/django.po
  cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
  cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_result.html
  cfgov/teachers_digital_platform/migrations/0026_add_activity_and_handout_document.py
  cfgov/teachers_digital_platform/models/activity_index_page.py
  cfgov/teachers_digital_platform/models/pages.py
  cfgov/teachers_digital_platform/templates/search/indexes/teachers_digital_platform/activitypage_text.txt
Labels: Back-end, Front-end
