Repository cfpb/consumerfinance.gov, pull requests merged in 2022-05, with the labels that each got.

#7007 HOLD: Deprecate Wagtail feedback form
  .github/workflows/functional-tests.yml
  cfgov/ask_cfpb/migrations/0040_deprecate_feedback_block.py
  cfgov/ask_cfpb/models/answer_page.py
  cfgov/data_research/forms.py
  cfgov/form_explainer/jinja2/form-explainer/index.html
  cfgov/form_explainer/migrations/0002_deprecate_feedback_block.py
  cfgov/form_explainer/models.py
  cfgov/hmda/jinja2/hmda/hmda-explorer.html
  cfgov/jinja2/v1/_includes/article.html
  cfgov/jinja2/v1/_includes/blocks/feedback.html
  cfgov/jinja2/v1/ask-cfpb/answer-page.html
  cfgov/jinja2/v1/browse-basic/index.html
  cfgov/jinja2/v1/browse-filterable/index.html
  cfgov/jinja2/v1/document-detail/index.html
  cfgov/jinja2/v1/enforcement-action/index.html
  cfgov/jinja2/v1/landing-page/index.html
  cfgov/jinja2/v1/learn-page/index.html
  cfgov/jinja2/v1/sublanding-page/index.html
  cfgov/locale/es/LC_MESSAGES/django.mo
  cfgov/locale/es/LC_MESSAGES/django.po
  cfgov/unprocessed/js/config/error-messages-config.js
  cfgov/unprocessed/js/routes/on-demand/feedback-form.js
  cfgov/v1/blocks.py
  cfgov/v1/forms.py
  cfgov/v1/handlers.py
  cfgov/v1/handlers/blocks/__init__.py
  cfgov/v1/handlers/blocks/feedback.py
  cfgov/v1/jinja2_environment.py
  cfgov/v1/migrations/0205_deprecate_feedback_block.py
  cfgov/v1/models/blog_page.py
  cfgov/v1/models/browse_filterable_page.py
  cfgov/v1/models/browse_page.py
  cfgov/v1/models/enforcement_action_page.py
  cfgov/v1/models/landing_page.py
  cfgov/v1/models/learn_page.py
  cfgov/v1/models/sublanding_filterable_page.py
  cfgov/v1/models/sublanding_page.py
  cfgov/v1/tests/handlers/__init__.py
  cfgov/v1/tests/handlers/blocks/__init__.py
  cfgov/v1/tests/handlers/blocks/test_feedback.py
  cfgov/v1/tests/models/test_base.py
  cfgov/v1/tests/test_handlers.py
  cfgov/v1/tests/test_wagtail_hooks.py
  cfgov/v1/tests/wagtail_pages/helpers.py
  cfgov/v1/tests/wagtail_pages/test_page_creation.py
  docs/editing-components.md
  test/cypress/integration/components/feedback/feedback-helpers.js
  test/cypress/integration/components/feedback/feedback.js
Labels: hold

#7008 HOLD: Deprecate Planning for Retirement feedback form
  cfgov/retirement_api/jinja2/retirement_api/claiming.html
  cfgov/retirement_api/locale/es/LC_MESSAGES/django.mo
  cfgov/retirement_api/locale/es/LC_MESSAGES/django.po
  cfgov/unprocessed/apps/analytics-gtm/js/retirement-before-you-claim-listeners.js
  cfgov/unprocessed/apps/retirement/js/views/next-steps-view.js
Labels: hold

#7044 Non government site url filter fix
  cfgov/ask_cfpb/tests/test_search.py
  cfgov/core/tests/test_utils.py
  cfgov/core/utils.py
Labels: Back-end

#7083 Broken jinja made only a single media_css file get included on a page
  cfgov/jinja2/v1/_layouts/base.html
  cfgov/v1/tests/models/test_base.py
Labels: [issue-type] bug
